### PR TITLE
Laravel 8 Support

### PR DESCRIPTION
**Pull request by jeremykenedy**
Laravel 8 Support

### CODE REVIEW

**Review by GavG — APPROVED** [review]
Tested in fresh and existing Laravel 8 environments, confirmed working as expected.

**Comment by spaantje** [comment]
Please merge this!

**Comment by neochief** [comment]
Done, thanks folks!

**Comment by godoyLeonardo** [comment]
in a non-clean installation of Laravel 8, I get this error when running composer install. 
`- Conclusion: install laravel/framework 5.7.x-dev`
Could someone help me?

**Comment by GavG** [comment]
@vipeeerr 

I don't think a tag/release has been made yet for L8 support, you could try requiring master / specific commit in composer or fork temporarily and create your own tag until one is made.

Hopefully @neochief could make a release? Pls :)

**Comment by neochief** [comment]
Sorry about that, I have created the release tag.

**Comment by neochief** [comment]
Frankly, I no longer can maintain this thing as  I used to. If anyone wants to jump in and help, please let me know.

**Comment by spaantje** [comment]
@neochief i would be able to help out if you want.

**Comment by neochief** [comment]
@spaantje, thanks! I've sent the invite to you.

**Pull request merged**
